
- name: Create inbox user {{ inbox_user }}
  user:
    name: "{{ inbox_user }}"
    create_home: no
    password_lock: yes
    system: yes
    shell: /bin/false

- name: Create inbox tmpfiles.d in {{ systemd_tmpfiles_dir }}
  template:
    src: inbox-tmpfiles.conf.j2
    dest: "{{ systemd_tmpfiles_dir }}/inbox.conf"
  register: inbox_tmpfiles

- name: Create inbox dirs in {{ inbox_root }}
  command: systemd-tmpfiles --create {{ inbox_tmpfiles.path }}
  args:
    creates: "{{ inbox_root }}"

- name: Create inbox config file in {{ inbox_cfgdir }}
  template:
    src: inbox-config.j2
    dest: "{{ inbox_cfgdir }}/inbox"

- name: Create scripts in {{ inbox_bindir }}
  template:
    src: "{{ item }}"
    dest: "{{ inbox_bindir }}/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: root
    mode: 0755
  with_items:
    - document-scanner.j2
    - handle-scan.j2
    - ingester.j2

- name: Create systemd service files in {{ systemd_unit_dir }}
  template:
    src: "{{ item }}"
    dest: "{{ systemd_unit_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: root
  with_items:
    - document-scanner.service.j2
    - ingest@.service.j2
  notify:
    - reload systemd

- name: Enable and start document-scanner service
  service: name=document-scanner state=started enabled=yes

